-- =====================================================
-- Migration: Add missing columns to match Java Entities
-- =====================================================

-- 1. Bookings table: Add DiscountAmount and DiscountCode
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'DiscountAmount')
BEGIN
    ALTER TABLE Bookings ADD DiscountAmount DECIMAL(10, 2) NOT NULL DEFAULT 0;
    PRINT 'Added Bookings.DiscountAmount';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Bookings' AND COLUMN_NAME = 'DiscountCode')
BEGIN
    ALTER TABLE Bookings ADD DiscountCode NVARCHAR(50) NULL;
    PRINT 'Added Bookings.DiscountCode';
END

-- 2. TourSchedules table: Add ReportSubmittedAt, CurrentProgress, ReportContent
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TourSchedules' AND COLUMN_NAME = 'ReportSubmittedAt')
BEGIN
    ALTER TABLE TourSchedules ADD ReportSubmittedAt DATETIME2 NULL;
    PRINT 'Added TourSchedules.ReportSubmittedAt';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TourSchedules' AND COLUMN_NAME = 'CurrentProgress')
BEGIN
    ALTER TABLE TourSchedules ADD CurrentProgress NVARCHAR(MAX) NULL;
    PRINT 'Added TourSchedules.CurrentProgress';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TourSchedules' AND COLUMN_NAME = 'ReportContent')
BEGIN
    ALTER TABLE TourSchedules ADD ReportContent NVARCHAR(MAX) NULL;
    PRINT 'Added TourSchedules.ReportContent';
END

-- 3. Tours table: Add missing columns
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'BestTime')
BEGIN
    ALTER TABLE Tours ADD BestTime NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.BestTime';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'WeatherInfo')
BEGIN
    ALTER TABLE Tours ADD WeatherInfo NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.WeatherInfo';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'GuideInfo')
BEGIN
    ALTER TABLE Tours ADD GuideInfo NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.GuideInfo';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'SuitableAges')
BEGIN
    ALTER TABLE Tours ADD SuitableAges NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.SuitableAges';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'WhyChooseUs')
BEGIN
    ALTER TABLE Tours ADD WhyChooseUs NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.WhyChooseUs';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Tips')
BEGIN
    ALTER TABLE Tours ADD Tips NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.Tips';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Itinerary')
BEGIN
    ALTER TABLE Tours ADD Itinerary NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.Itinerary';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'PaymentPolicy')
BEGIN
    ALTER TABLE Tours ADD PaymentPolicy NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.PaymentPolicy';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'CancellationPolicy')
BEGIN
    ALTER TABLE Tours ADD CancellationPolicy NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.CancellationPolicy';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'ChildPolicy')
BEGIN
    ALTER TABLE Tours ADD ChildPolicy NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.ChildPolicy';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Inclusions')
BEGIN
    ALTER TABLE Tours ADD Inclusions NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.Inclusions';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Exclusions')
BEGIN
    ALTER TABLE Tours ADD Exclusions NVARCHAR(MAX) NULL;
    PRINT 'Added Tours.Exclusions';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'OriginalPrice')
BEGIN
    ALTER TABLE Tours ADD OriginalPrice DECIMAL(10, 2) NULL;
    PRINT 'Added Tours.OriginalPrice';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'HasPickup')
BEGIN
    ALTER TABLE Tours ADD HasPickup BIT NOT NULL DEFAULT 0;
    PRINT 'Added Tours.HasPickup';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'HasLunch')
BEGIN
    ALTER TABLE Tours ADD HasLunch BIT NOT NULL DEFAULT 0;
    PRINT 'Added Tours.HasLunch';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'IsInstantConfirmation')
BEGIN
    ALTER TABLE Tours ADD IsInstantConfirmation BIT NOT NULL DEFAULT 0;
    PRINT 'Added Tours.IsInstantConfirmation';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'IsDaily')
BEGIN
    ALTER TABLE Tours ADD IsDaily BIT NOT NULL DEFAULT 0;
    PRINT 'Added Tours.IsDaily';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'MinDepositRate')
BEGIN
    ALTER TABLE Tours ADD MinDepositRate DECIMAL(5, 2) NULL;
    PRINT 'Added Tours.MinDepositRate';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'RefundGracePeriod')
BEGIN
    ALTER TABLE Tours ADD RefundGracePeriod INT NULL;
    PRINT 'Added Tours.RefundGracePeriod';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'MetaTitle')
BEGIN
    ALTER TABLE Tours ADD MetaTitle NVARCHAR(200) NULL;
    PRINT 'Added Tours.MetaTitle';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'MetaDescription')
BEGIN
    ALTER TABLE Tours ADD MetaDescription NVARCHAR(500) NULL;
    PRINT 'Added Tours.MetaDescription';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'TransportType')
BEGIN
    ALTER TABLE Tours ADD TransportType NVARCHAR(50) NULL;
    PRINT 'Added Tours.TransportType';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Latitude')
BEGIN
    ALTER TABLE Tours ADD Latitude DECIMAL(9, 6) NULL;
    PRINT 'Added Tours.Latitude';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Longitude')
BEGIN
    ALTER TABLE Tours ADD Longitude DECIMAL(9, 6) NULL;
    PRINT 'Added Tours.Longitude';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'Source')
BEGIN
    ALTER TABLE Tours ADD Source NVARCHAR(50) NULL;
    PRINT 'Added Tours.Source';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tours' AND COLUMN_NAME = 'ExternalId')
BEGIN
    ALTER TABLE Tours ADD ExternalId NVARCHAR(100) NULL;
    PRINT 'Added Tours.ExternalId';
END

-- 4. Categories: make Description NVARCHAR to support Unicode
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categories' AND COLUMN_NAME = 'Description' AND DATA_TYPE = 'varchar')
BEGIN
    ALTER TABLE Categories ALTER COLUMN Description NVARCHAR(MAX) NULL;
    PRINT 'Converted Categories.Description to NVARCHAR';
END

PRINT 'Migration complete!';
